[package]
name = "Rust-Back-End"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.0"
actix-cors = "0.7.1"
env_logger = "0.9"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"